apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: prometheus-smartctl-exporter
  repo: https://prometheus-community.github.io/helm-charts
  version: 0.13.0
  releaseName: smartctl-exporter
  valuesFile: helmvalues.yaml
  namespace: monitoring
resources:
  - prometheusrule.yaml
